name: Add ready to merge label

on:
  pull_request_review:
    types: [submitted]

jobs:
  modify_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Remove previous labels
        uses: rogerluan/label-remover@v1.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add labels
        uses: actions-ecosystem/action-add-labels@v1
        if: github.event.review.state == 'approved'
        with:
          labels: READY TO MERGE
