name: Add merged label

on:
  pull_request:
    types: closed

jobs:
  if_merged:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create list of labels
        id: get_list_of_labels
        uses: lucaspinheirogit/list-from-string-array-action@v1.4.3
        with:
          stringArray: ${{ toJSON(github.event.pull_request.labels.*.name) }}
      - name: Remove labels
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: echo '${{ steps.get_list_of_labels.outputs.stringList }}'
      - name: Add labels
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            MERGED
