name: Add merged label

on:
  pull_request:
    types: closed

jobs:
  if_merged:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Add labels
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            MERGED
      - name: echo labels
        run: echo ${{ github.event.pull_request.labels.*.name }}
      - name: Remove labels
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: github.event.pull_request.labels.*.name
